import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';

import 'app/app.dart';
import 'app/config/app_config.dart';
import 'core/auth/entra_auth_provider.dart';
import 'core/network/api_client.dart';
import 'core/network/session_token_adapter.dart';
import 'core/platform/url_strategy.dart';
import 'core/services/contracts.dart';
import 'core/services/mock_auth_provider.dart';
import 'core/services/mock_analytics_tracker.dart';
import 'core/services/mock_campus_repository.dart';
import 'core/services/rest_campus_repository.dart';
import 'core/services/site_settings_store.dart';
import 'core/services/url_launcher_map_provider.dart';

// Optional Firebase imports; the app will attempt to initialize Firebase if
// available. Real credentials (firebase_options.dart) should be generated by
// FlutterFire CLI and placed under lib/.
import 'package:firebase_core/firebase_core.dart' show Firebase;

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  configureUrlStrategy();

  // Real web split: visiting /admin (vs the normal / root) is a genuinely
  // separate entry point, not just a hidden button — see _DemoSession's
  // handling of `startInAdminMode` in app.dart for the actual role check.
  final startInAdminMode = kIsWeb && Uri.base.path.startsWith('/admin');

  // Attempt Firebase initialization; swallow errors so missing config won't
  // block running the demo app. For production, provide generated
  // `firebase_options.dart` and proper platform files (google-services.json / Info.plist).
  // Deliberately not logged: no Firebase project is configured in this
  // prototype (see docs/FIREBASE_SETUP.md and docs/GERCEK_PROJEYE_GECIS.md
  // §7) — this is an expected, disclosed condition, not an error to alert on.
  try {
    await Firebase.initializeApp();
  } catch (_) {
    // Push notifications simply stay unavailable until a real project exists.
  }

  // Real Entra sign-in switches on automatically once an admin fills in
  // Tenant ID / Client ID / Redirect URI from Profile → Yönetim Paneli →
  // Site Settings — no code change or rebuild needed for the credentials
  // themselves (the redirect scheme is still fixed at Android build time,
  // see android/app/build.gradle.kts). Until then this is empty and the app
  // keeps using the mock directory, exactly as before.
  final entraConfig = await SiteSettingsStore.entra();
  final AuthProvider authProvider;
  if (entraConfig.isConfigured) {
    authProvider = EntraAuthProvider(
      tenantId: entraConfig.tenantId,
      clientId: entraConfig.clientId,
      redirectUri: entraConfig.redirectUri,
    );
  } else {
    authProvider = MockAuthProvider();
  }

  // Real backend is the default: mock-only `flutter run` needs
  // `--dart-define=USE_REST_API=false`. Android emulator: API_BASE_URL=
  // http://10.0.2.2:4000/api/v1 ; web/desktop: http://localhost:4000/api/v1
  // Real, per-user session auth (docs/EKSIKLER.md "Gerçek JWT/session
  // authentication"): every request now carries whatever real bearer token
  // SessionStore holds — set once sign-in completes (see app.dart's
  // _finishSignIn), read fresh on every call since it doesn't exist yet
  // at this point in startup.
  const useRestApi = bool.fromEnvironment('USE_REST_API', defaultValue: true);
  const apiBaseUrl =
      String.fromEnvironment('API_BASE_URL', defaultValue: 'http://10.0.2.2:4000/api/v1');
  final CampusRepository repository = useRestApi
      ? RestCampusRepository(
          client: ApiClient(baseUrl: apiBaseUrl, authTokenAdapter: SessionTokenAdapter()))
      : MockCampusRepository();

  runApp(
    ArucadCampusApp(
      config: AppConfig.demo(),
      repository: repository,
      authProvider: authProvider,
      mapProvider: const UrlLauncherMapProvider(),
      analyticsTracker: MockAnalyticsTracker(),
      startInAdminMode: startInAdminMode,
    ),
  );
}

// Note: `firebase_messaging` usage removed due to web interop compile issues.
// Re-enable and test messaging when compatible web packages are available.
